name: Jira Issue Linker

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  jira-issue-link:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - run: npm run build
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
